before_script:

  - rm -f ../*.changes
  - sed -E -i 's/httpredir.debian.org/ftp.de.debian.org/g' /etc/apt/sources.list

  - apt-get update
  - apt-get install --yes --no-install-recommends build-essential equivs devscripts git-buildpackage ca-certificates pristine-tar git dpkg-dev coreutils ssh dput
  - DEBIAN_FRONTEND=noninteractive mk-build-deps --install --remove --tool 'apt-get --no-install-recommends --yes' debian/control
  - git describe

run_tests:
  image: debian:jessie
  script:
    - perl Makefile.PL
    - make test
