sudo: required

services:
  - docker

env:
  matrix:
    - TRAVIS_DEBIAN_DISTRIBUTION=wheezy DPUT=1
    - TRAVIS_DEBIAN_DISTRIBUTION=jessie DPUT=1
    - TRAVIS_DEBIAN_DISTRIBUTION=sid DPUT=0


before_install:
  - sudo apt-get -qq --yes install devscripts dpkg-dev
  - dch --newversion `git describe|sed -E 's#.*/##'|sed -E 's/-([0-9]+)-(.{8})$/+\1.\2/'`~$TRAVIS_DEBIAN_DISTRIBUTION --force-distribution --distribution nowtaxi-$TRAVIS_DEBIAN_DISTRIBUTION 'Autobuilt by git commit' 
  - git commit -m 'update changelog' debian/changelog
  - dpkg-parsechangelog

script:
  - wget -O- http://travis.debian.net/script.sh | sh -
  - ls -lR
  - pwd
  - echo $TRAVIS_DEBIAN_DISTRIBUTION
  - ls -l ..
  
  - echo $UPLOAD_SSH_KEY | base64 -d > ../issh
  - chmod 0600 ../issh

  - echo '[nowtaxi-jessie]' > ../dput.cf
  - echo login = gitlabuploader >> ../dput.cf
  - echo fqdn = debian.nowtaxi.ru >> ../dput.cf
  - echo method = scp >> ../dput.cf
  - echo incoming = /srv/debian.incomming/jessie >> ../dput.cf
  - echo ssh_config_options = UserKnownHostsFile=/dev/null >> ../dput.cf
  - echo '     StrictHostKeyChecking=no' >> ../dput.cf
  - echo '     IdentityFile=../issh'  >> ../dput.cf

  - echo '[nowtaxi-wheezy]' >> ../dput.cf
  - echo login = gitlabuploader >> ../dput.cf
  - echo fqdn = debian.nowtaxi.ru >> ../dput.cf
  - echo method = scp >> ../dput.cf
  - echo incoming = /srv/debian.incomming/wheezy >> ../dput.cf
  - echo ssh_config_options = UserKnownHostsFile=/dev/null >> ../dput.cf
  - echo '     StrictHostKeyChecking=no' >> ../dput.cf
  - echo '     IdentityFile=../issh'  >> ../dput.cf

  - echo '[nowtaxi-stretch]' >> ../dput.cf
  - echo login = gitlabuploader >> ../dput.cf
  - echo fqdn = debian.nowtaxi.ru >> ../dput.cf
  - echo method = scp >> ../dput.cf
  - echo incoming = /srv/debian.incomming/stretch >> ../dput.cf
  - echo ssh_config_options = UserKnownHostsFile=/dev/null >> ../dput.cf
  - echo '     StrictHostKeyChecking=no' >> ../dput.cf
  - echo '     IdentityFile=../issh'  >> ../dput.cf

  - if test "$DPUT" -eq 1; then dput --debug -u -c ../dput.cf nowtaxi-$TRAVIS_DEBIAN_DISTRIBUTION ../*.changes; fi

  - cat ../*.changes

branches:
  only:
    - master
